### PR TITLE
fixed userinfo regex for @ character in userinfo

### PR DESCRIPTION
**Pull request by cansarigol**
`USERINFO_RE` regex pattern separates URL by first @ character. I changed this pattern to evaluate the last @ character so that can use an email address for userinfo.username (e.g. "https://user@gmail.com:password@example.com")

### CODE REVIEW

**Comment by cansarigol** [comment]
HI @sethmlarson could you review this pr.

**Comment by sigmavirus24** [comment]
There's no description for why this is important. All it says is that it "Fixed" something which is correct per the ABNF.

**Comment by cansarigol** [comment]
This fix about using email address for userinfo.username 
e.g. "https://user@gmail.com:password@example.com". Email address is quite used as a username.  But using in url I'm not sure. Hence I don't know how important it is.

in Httpx project we had a problem with this ([issue328](https://github.com/encode/httpx/issues/328)) and as per ticket, @sethmlarson wrote that we can fix `rfc3986`. Because of that, I wanted to push a commit to fix this problem.

As far as I understood, `USERINFO_RE`  regex pattern separates URL by first @ character. I changed this pattern to evaluate the last @ character.

**Comment by sigmavirus24** [comment]
That's all great context that belongs in the commit message and pull request description.

**Comment by oczkers** [comment]
Can we get it merged?

**Comment by sigmavirus24** [comment]
This is still not compliant with the RFC. The @ in the email must be encoded for it to be passed correctly

**Pull request closed without merging**
