### PR TITLE
Add release notes for 2.0.1

### PR DESCRIPTION
**Pull request by handrews**
Addresses #107

### CODE REVIEW

**Comment by handrews** [comment]
Hit submit by accident... @sigmavirus24 I wasn't sure what to put for the date and assumed that you'd set it correctly and change the version in the package meta-data.  If you want me do do something else here, please let me know.

**Comment by handrews** [comment]
I'm not sure what to do about the docs build failure as I don't know what an "intersphinx mapping" is and clicking through the link in the error log did not clarify things 😅 😬

**Comment by handrews** [comment]
@sigmavirus24 or anyone, any update on this?  I am happy to do something about the docs check failure if anyone can give me a pointer on how to debug "intersphinx mapping".

**Comment by sigmavirus24** [comment]
@handrews that would be helpful. The relevant configuration is https://github.com/python-hyper/rfc3986/blob/bd8154357fe22d9b4d344b0e6e9fc1fc7ee575c5/docs/source/conf.py#L170 

It seems the format has changed per the message

```
Failed to read intersphinx_mapping[https://docs.python.org/], ignored: SphinxWarning('The pre-Sphinx 1.0 \'intersphinx_mapping\' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {\'<name>\': (\'[https://docs.python.org/\](https://docs.python.org//)', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping')
```

I suspect the documentation liink explains how to fix it. Namely, I'd guess the first example in the docs:

```
intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}
```

Is something like what we'd want

**Comment by handrews** [comment]
OK, this should be good to go.  My apologies for not noticing the sphinx conf matching the error - for some reason Sphinx routinely frustrates me so much that I miss the obvious every time something goes wrong with it.

**Pull request merged**
