### PR TITLE
Stopped abnf regex from halting when it encounters a line terminator in the fragment

### LINKED ISSUE #99: Parsing of fragments through ParseResult.fromString can be cut short by a newline character
# Background

According to RFC 3986 line termination characters like ```\n``` are not allowed in any part of a URI but the percent-encoded versions ```%0A``` are allowed. For other sections of the URL, such as the query and the path, ParseResult.fromString will normalize ```\n``` characters into percent-encoded characters and accept them. This is not true for the fragment section of the URI.

# The Bug

Inserting any line termination character into the fragment section of the URL will result in the parsing of the fragment section being cut short.

## Minimal Reproducible Example

```python
import rfc3986
# Arguments are (URL, encoding, strict, lazy_normalize)
parsed_url = rfc3986.ParseResult.from_string('scheme://user@host.com:80/path?query#Fragment\nThatIsIllusive', 'utf-8', True, False)
print("Fragment: " + parsed_url.fragment)
```
This will print ```Fragment: Fragment```

In contrast Furl, Hyperlink, Urllib, and Yarl all return ```Fragment: Fragment%0AThatIsIllusive```

## Cause

This is the regex used to parse different parts of a URI

```python
SCHEME_RE = "[a-zA-Z][a-zA-Z0-9+.-]*"
_AUTHORITY_RE = "[^\\\\/?#]*"
_PATH_RE = "[^?#]*"
_QUERY_RE = "[^#]*"
_FRAGMENT_RE = ".*"
```

This bug is a result of the use of ```.*``` in the fragment regex. The ```.``` symbol in regex accepts every character except for line termination characters.

### PR DESCRIPTION
**Pull request by JohnJamesUtley**
fixes #99

### CODE REVIEW

**Comment by sigmavirus24** [comment]
`DOTALL` is a sledgehammer. We should use `(?s:.*)` for the fragment matching _if_ we actually want to allow newlines there. I'm not convinced we should.

**Comment by JohnJamesUtley** [comment]
> `DOTALL` is a sledgehammer. We should use `(?s:.*)` for the fragment matching _if_ we actually want to allow newlines there. I'm not convinced we should.

You are absolutely correct that DOTALL is too much and the inline flag is a much cleaner solution. I've switched the pull request to amend that just now.

The change is necessary because in other similar sections of the URL, such as the query and the path, line termination characters are accepted and are converted into percent-encoded characters when the path and query are returned. It is inconsistent that the fragment section treats these same characters differently.

I would expect line termination characters in the fragment to be percent-encoded like they are in the query and the path.

Additionally, the other Python URL parsers handle line termination characters in the fragment section by converting them to percent-encoded characters in their output. Ending the parsing at line termination characters in the fragment section instead of percent-encoding them is strange behavior in my opinion. Especially since line termination characters elsewhere in the URL do not end the parsing.
(I tested Furl, Hyperlink, Urllib, and Yarl).

**Comment by sigmavirus24** [comment]
Can you add a test case or two?

**Comment by JohnJamesUtley** [comment]
@sigmavirus24 Made the changes you requested 👍

**Review by sigmavirus24 — APPROVED** [review]

**Pull request merged**
