### PR TITLE
Bump version to 1.2.0

### PR DESCRIPTION
**Pull request by sethmlarson**
@sigmavirus24 I listed the date as 2018-12-07 to give you plenty of time to run the release automation if you want to merge this as-is. If you want me to change to a different release day just ping me and I'll amend the commit. Thanks for reviewing all these changes. :)

### CODE REVIEW

**Comment by SethMichaelLarson** [comment]
Did you mean to use !35 for the link?

**Comment by sigmavirus24** [comment]
Yes. It wasn't an issue or linked to one, and GitLab uses ! for 'merge requests' so I figured I'd see if that makes it easier to understand the sources of things.

**Comment by sigmavirus24** [comment]
1.2.0 is live on PyPI!

**Comment by SethMichaelLarson** [comment]
@sigmavirus24 Woo! Also TIL about the merge request notation, I need to explore GitLab more.

**Comment by SethMichaelLarson** [comment]
Should I point the release and tag at 0d82fee then?

**Comment by SethMichaelLarson** [comment]
Not to be one of those people but aren't there already releases created for the project? I'm looking at the main page and it says 9 releases.

**Comment by sigmavirus24** [comment]
Those are just tags. GitHub wants to pretend people creating tags are using their crappy feature

**Comment by SethMichaelLarson** [comment]
Is there even a mechanism to tag commits via pull requests? I don't have commit access so I can't push tags, maybe I'm misunderstanding something.

**Comment by sigmavirus24** [comment]
> Is there even a mechanism to tag commits via pull requests?

No.

> I don't have commit access so I can't push tags, maybe I'm misunderstanding something.

Per the hyper policy, I added you to the team. You should have commit access now.

**Comment by sigmavirus24** [comment]
Thank you!

**Pull request merged**
